config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  root 'hiro#qr_reader'

  get 'hiro/index/:image_id' => 'hiro#index'
  get 'qr_reader' => 'hiro#qr_reader'

  resources :images, only: %i[index create new show]
  get 'images/:image_id' => 'images#show', as: 'show_image'

  resources :qr, only: %i[new show]
  get 'download/:image_id' => 'qr#download'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  validates :name, :image, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ar_code_controller.rb
class ArCodeController < ApplicationController
  IMAGE_NOT_EXISTS = 'You are trying to encode a not existing image'
  QR_IMAGE_PATH = 'public/qr_codes/'

  def show
    @id = params[:id]
    unless Image.exists? @id
      redirect_to images_path, error: IMAGE_NOT_EXISTS
    end
    generate_qr_ar_image(@id)

    @ar_url = root_url + "qr_codes/hiro#{@id}.png"
  end

  def generate_qr_ar_image(image_id)
    image_path = "#{QR_IMAGE_PATH + image_id}.png"
    Qr4r::encode(image_id, image_path, pixel_size: 20)

    #this will be the final image
    big_image = Magick::ImageList.new

    image_row = Magick::ImageList.new
    image_row.push(Magick::Image.read("#{QR_IMAGE_PATH + image_id}.png").first)
    image_row.push(Magick::Image.read('app/assets/images/hiro.png').first)

    big_image.push(image_row.append(false))

    big_image.append(true).write("public/qr_codes/hiro#{image_id}.png")
  end

  def download
    send_file (QR_IMAGE_PATH + 'hiro' + params[:image_id] + '.png')
  end

end

app/controllers/hiro_controller.rb
class HiroController < ApplicationController
  def index
    @image_url = find_image_from_url.image_url
  end

  private

  def find_image_from_url
    Image.find(params[:image_id])
  rescue ActiveRecord::RecordNotFound
    Image.last
  end
end

app/controllers/images_controller.rb
require 'rmagick'

class ImagesController < ApplicationController

  def index
    @images = Image.all
  end
  
  def new
    @image = Image.new
  end

  def show
    @image = Image.find(params[:id])
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to show_image_path(image_id: @image.id)
    else
      render :new
    end
  end

  private

  def image_params
    params.require(:image).permit(:name, :image)
  end
end

app/controllers/qr_controller.rb
class QrController < ApplicationController
  IMAGE_NOT_EXISTS = 'You are trying to encode a not existing image'
  QR_IMAGE_PATH = 'public/qr_codes/'

  def show
    @id = params[:id]
    redirect_to images_path, error: IMAGE_NOT_EXISTS unless Image.exists?(@id)
    generate_qr_ar_image(@id)
    @ar_url = root_url + "qr_codes/hiro#{@id}.png"
  end

  def generate_qr_ar_image(image_id)
    image_path = "#{QR_IMAGE_PATH + image_id}.png"
    Qr4r::encode(image_id, image_path, pixel_size: 20)

    #this will be the final image
    big_image = Magick::ImageList.new

    image_row = Magick::ImageList.new
    image_row.push(Magick::Image.read("#{QR_IMAGE_PATH + image_id}.png").first)
    image_row.push(Magick::Image.read('app/assets/images/hiro.png').first)

    big_image.push(image_row.append(false))

    big_image.append(true).write("public/qr_codes/hiro#{image_id}.png")
  end

  def download
    send_file(QR_IMAGE_PATH + 'hiro' + params[:image_id] + '.png')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @image_url = find_image_from_url.image_url
  end

  private

  def find_image_from_url
    Image.find(params[:image_id])
  rescue ActiveRecord::RecordNotFound
    Image.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hiro/index.html.erb
<html>
  <body class="hiro-scene">
    <a-scene embedded artoolkit='sourceType: webcam;'>
      <a-image geometry="primitive:box; width:1; height:1; depth:1" src=<%= asset_path @image_url %>></a-image>
      <a-marker-camera preset='hiro'></a-marker-camera>
    </a-scene>
  </body>
</html>

app/views/hiro/qr_reader.html.erb
<html>
  <body>
    <div onclick="tooglePopUp()">
      <video id="preview" class="qr_video"></video>
      <div id="popUp" class="modal">
        <%= render 'shared/navbar' %>

        <div class="modal-content">
          <div class="modal-title"><span>  Select one of your available cameras and point to a Tsundoku QR code </span></div>
          <div id="chooseCamera"></div>
        </div>
      </div>
    </div>
  </body>
</html>

<script type="text/javascript">
    var popUpText = "<div><span id='myPopup' class='modal-text' data-devise={deviseId} onclick='startScaning(this)'>&gt &nbsp {deviseName}</span><div>";
    var scanner;

    $(document).ready(function () {
        var preview = document.getElementById('preview');
        if (preview) {
            scanner = new Instascan.Scanner({video: preview, mirror: false});

            scanner.addListener('scan', function (content) {
                window.location.href = "<%= root_url %>hiro/index/" + content;
            });

            Instascan.Camera.getCameras().then(function (cameras) {
                if (cameras.length > 0) {
                    userSelectDevise(cameras);
                } else {
                    alert('No cameras found.');
                }
            }).catch(function (e) {
                console.error(e);
            });
        }
    });

    var devises;

    function userSelectDevise(cameras) {
        devises = cameras;
        var popup = $("#chooseCamera");
        var cameraName;

        for (var i = 0; i < cameras.length; i++) {
            console.log(cameras[i].name);
            if(cameras[i].name != undefined || cameras[i].name != null){
                cameraName = cameras[i].name;
            }else{
                cameraName = "Camera " + (i + 1);
            }
            var deviseText = popUpText.supplant({deviseId: cameras[i].id, deviseName: cameraName});
            popup.append(deviseText);
        }
    }

    function startScaning(selectedDeviseElement) {
        var selectedDeviseId = selectedDeviseElement.dataset.devise;
        var selectedDevise;
        for(var i = 0; i < devises.length; i++){
            if(devises[i].id == selectedDeviseId){
                selectedDevise = devises[i];
            }
        }

        if(selectedDevise == undefined || selectedDevise == null){
            alert("Fatal error finding camera, please reload the app");
        }else{
            scanner.start(selectedDevise);
        }
    }

    function tooglePopUp() {
        $("#popUp").toggle();
    }
</script>

app/views/images/index.html.erb
<% unless flash[:notice].blank? %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

<%= render 'shared/navbar' %>

<div class="image-gallery">
  <%= link_to 'New Image', new_image_path, class: 'center btn' %>

  <table>
      <% @images.each do |image| %>
        <tr>
          <td style="width: 10%"><%= image.id %></td>
          <td style="width: 20%"><%= image.name %></td>
          <td><%= image_tag image.image_url %></td>
          <td style="width: 20%"><%= link_to 'Show URL', image_path(id: image.id) %></td>
          <td style="width: 20%"><%= link_to 'Show QR', controller: 'qr', action: 'show', :id => image.id %></td>
        </tr>
      <% end %>
  </table>
</div>

<script type="text/javascript">
  if(typeof scanner !== "undefined"){scanner.stop();}
</script>

app/views/images/new.html.erb
<% unless @image.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'shared/navbar' %>

<div class="upload-image">
  <%= form_for @image, html: { multipart: true } do |f| %>
    <%= f.text_field :name, placeholder: 'Your image name' %>
    <%= f.file_field :image %>
      <div class="with-padding">
        <%= link_to 'Back', images_path, class: 'btn' %>
        <%= f.submit 'Submit', class: 'btn' %>
      </div>
  <% end %>
</div>

app/views/images/qr.html.erb
<% unless flash[:notice].blank? %>
      <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>

<div class="image-gallery">
  <div class="ar-qr-image center">
    <%= image_tag @qr_url%>
  </div>
  <%= link_to 'Back', images_path, class: 'btn center' %>
</div>

app/views/images/show.html.erb
<% unless @image.errors.empty? %>
    <div class="alert alert-error">
      <ul>
        <% @image.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= render 'shared/navbar' %>

<div class="image-gallery">
  <ul>
    <li><%= image_tag @image.image_url %></li>
    <li><%= link_to 'Image link', @image.image_url %></li>
  </ul>
</div>

<%= link_to 'Back', images_path, class: 'btn center' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GrupalTsundoku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/qr/show.html.erb
<% unless flash[:notice].blank? %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
<% end %>

<%= render 'shared/navbar' %>

<div class="image-gallery">
  <div class="ar-qr-image">
    <%= image_tag @ar_url%>
  </div>
  <div class="input-group">
    <%= text_field_tag 'ar url', @ar_url %>
    <button onclick="setClipboardText()">Copy link to clipboard</button>
  </div>
  <div class="button-container">
      <%= link_to 'Download', {:action => :download, :image_id =>@id}, class: 'button-left btn'%>
    <%= link_to 'Back', images_path, class: 'btn button-right' %>
  </div>
</div>

<script type="text/javascript">
    function setClipboardText(){
        var id = "cp_to_clipboard";
        var text = "<%= @ar_url %>";
        var existsTextarea = document.getElementById(id);

        if(!existsTextarea){
            var textarea = document.createElement("textarea");
            textarea.id = id;
            // Place in top-left corner of screen regardless of scroll position.
            textarea.style.position = 'fixed';
            textarea.style.top = 0;
            textarea.style.left = 0;

            // Ensure it has a small width and height. Setting to 1px / 1em
            // doesn't work as this gives a negative w/h on some browsers.
            textarea.style.width = '1px';
            textarea.style.height = '1px';

            // We don't need padding, reducing the size if it does flash render.
            textarea.style.padding = 0;

            // Clean up any borders.
            textarea.style.border = 'none';
            textarea.style.outline = 'none';
            textarea.style.boxShadow = 'none';

            // Avoid flash of white box if rendered for any reason.
            textarea.style.background = 'transparent';
            document.querySelector("body").appendChild(textarea);
            existsTextarea = document.getElementById(id);
        }

        existsTextarea.value = text;
        existsTextarea.select();

        try {
            var status = document.execCommand('copy');
            if(!status){
                alert("Error trying to copy");
            }else{
                alert("The text is now on the clipboard");
            }
        } catch (err) {
            console.log('Unable to copy.');
        }
    }
</script>

app/views/shared/_navbar.html.erb
<div class="topnav">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Images', images_path %>
</div>

app/views/welcome/qr_reader.html.erb
<html>
  <body>
    <div onclick="tooglePopUp()">
      <video id="preview" class="qr_video"></video>
      <div id="popUp" class="modal">
        <%= render 'shared/navbar' %>

        <div class="modal-content">
          <div class="modal-title"><span>  Select one of your available cameras and point to a Tsundoku QR code </span></div>
          <div id="chooseCamera"></div>
        </div>
      </div>
    </div>
  </body>
</html>

<script type="text/javascript">
    var popUpText = "<div><span id='myPopup' class='modal-text' data-devise={deviseId} onclick='startScaning(this)'>&gt &nbsp {deviseName}</span><div>";
    var scanner;

    $(document).ready(function () {
        var preview = document.getElementById('preview');
        if (preview) {
            scanner = new Instascan.Scanner({video: preview, mirror: false});

            scanner.addListener('scan', function (content) {
                window.location.href = "<%= root_url %>welcome/index/" + content;
            });

            Instascan.Camera.getCameras().then(function (cameras) {
                if (cameras.length > 0) {
                    userSelectDevise(cameras);
                } else {
                    alert('No cameras found.');
                }
            }).catch(function (e) {
                console.error(e);
            });
        }
    });

    var devises;

    function userSelectDevise(cameras) {
        devises = cameras;
        var popup = $("#chooseCamera");
        var cameraName;

        for (var i = 0; i < cameras.length; i++) {
            console.log(cameras[i].name);
            if(cameras[i].name != undefined || cameras[i].name != null){
                cameraName = cameras[i].name;
            }else{
                cameraName = "Camera " + (i + 1);
            }
            var deviseText = popUpText.supplant({deviseId: cameras[i].id, deviseName: cameraName});
            popup.append(deviseText);
        }
    }

    function startScaning(selectedDeviseElement) {
        var selectedDeviseId = selectedDeviseElement.dataset.devise;
        var selectedDevise;
        for(var i = 0; i < devises.length; i++){
            if(devises[i].id == selectedDeviseId){
                selectedDevise = devises[i];
            }
        }

        if(selectedDevise == undefined || selectedDevise == null){
            alert("Fatal error finding camera, please reload the app");
        }else{
            scanner.start(selectedDevise);
        }
    }

    function tooglePopUp() {
        $("#popUp").toggle();
    }
</script>